name: Daily PowerShell Linting

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  # Also allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PowerShell and PSScriptAnalyzer
        # Installs PowerShell and the linter module
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell
          pwsh -Command "Install-Module -Name PSScriptAnalyzer -Force"

      - name: Run PowerShell linter
        # Finds all .ps1 files and runs the linter on them
        run: |
          echo "Running PSScriptAnalyzer..."
          pwsh -Command "Get-ChildItem -Path . -Recurse -Filter '*.ps1' | ForEach-Object {Invoke-ScriptAnalyzer -Path $_.FullName}"
